### ISSUE TITLE
sp_Blitz.sql - DB Output to Local Server Fails

### ISSUE THREAD

**Issue by GysmoSan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1128]
sp_Blitz.sql - @Version = '5.0'; @VersionDate = '20170307'

If I use only @OutputDatabaseName, @OutputSchemaName and @OutputTableName to populate a table on the same server leaving @OutputServerName as the default = NULL I get the following;

EXEC [dbo].[sp_Blitz]
@OutputDatabaseName = 'DatabaseName ,
@OutputSchemaName = 'dbo' ,
@OutputTableName = 'TableName'

Msg 257, Level 16, State 3, Line 1
Implicit conversion from data type xml to nvarchar(max) is not allowed. Use the CONVERT function to run this query.

This works normally if sending to a linked server (which you cant for local, that way lies madness ;p)

I've tracked through the stored procedure logic and found the solution :-)

This works:
Line 6189: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **CAST(QueryPlan AS NVARCHAR(MAX))**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

This fails:
Line 6204: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **QueryPlan**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

The "CAST(QueryPlan AS NVARCHAR(MAX))" portion if added solves things... :-)

This one might want the same fix...
Line 6239: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **QueryPlan**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

NB The server in question is running SQL Server 12.0.2480.0 if it makes a difference...

Martin

**Comment by BlitzErik** [comment]
Martin,

You're several versions/months behind. Can you update to a more recent version and try again? I believe this was fixed a while back. I'm mobile at the moment and can't really search.

Thanks,
Erik

**Comment by GysmoSan** [comment]
Appologies, I checked the code I found here which only had the first one fixed and the version I'm using I thought was freshly downloaded last week. I'm probably using the wrong link 

New to GitHub *goes hunting*

**Comment by GysmoSan** [comment]
2017-09 Sourced and possibly still an issue though I'll now test with that version and confirm :-);

Line 7471: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **CAST(QueryPlan AS NVARCHAR(MAX))**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

Line 7486: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **QueryPlan**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

Line 7521: + ''', SYSDATETIMEOFFSET(), CheckID, DatabaseName, Priority, FindingsGroup, Finding, URL, Details, **QueryPlan**, QueryPlanFiltered FROM #BlitzResults ORDER BY Priority , FindingsGroup , Finding , Details';

**Comment by BrentOzar** [comment]
Sorry, but we're not going to output the query plan as nvarchar. Having it as xml lets people click on it and see the output. If you want to get the sp_Blitz results over linked servers, your best bet is to write it directly to a table on the server where you're running it, and then query that result table over linked servers. Thanks!

**Comment by GysmoSan** [comment]
"Your best bet is to write it directly to a table on the server where you're running it"

Sorry,  to be clear, 

It works fine over linked servers to table perfectly using the existant "CAST(QueryPlan AS NVARCHAR(MAX))" (and it's awesome btw); 

Alas it doesn't work to your suggested local DB which just has plan vinilla QuertPlan.

I was just pointing out an inconsistancy between load methods. If it's meant to be different then no worries

**Comment by BrentOzar** [comment]
Yep, as designed. Thanks!

**Comment by GysmoSan** [comment]
Brent,

Ah, I now appreciate the issue;

Pass 1: Build SQL to create a table if missing including XML data type but then change that to NVarchar if its a remote server (@ValidOutputServer = 1);
If a remote server (@ValidOutputServer = 1), build the query to populate the table casting QueryPlan as NVarchar to match the tweaked build.

Pass 2: If a local server (else, or implied @ValidOutputServer = NULL)
build the query to populate the table leaving QueryPlan as is...

Net effect; 

If the first create is to a remote DB it will be stored as NVarchar, and only work for remote loads... (Local loads will give Implicit conversion from data type xml to nvarchar(max) is not allowed. Use the CONVERT function to run this query.)

If the first create is to a local DB it will be stored as XML and will not take loads from a remote call (This would generate errors in the form; Msg 9514, Level 16, State 1, Line 1. Xml data type is not supported in distributed queries. Remote object 'C-Scuda-TWSQL2\DB2A.Server_Checker.dbo.Blitz_Report_Findings' has xml column(s).")

You're only catering for the first one due to that exact issue. I concede that for backward compatability there might be issue if the table exists as it will be XML with data supplied as NVarchar if remote loads are later attempted...

I'll look at a remote DB on both nodes of out main SQL cluster and load to the oposite one for the two main nodes. All the other SQL server can load to either :-) Would be nice to have one DB for all of them however...

The TABLE and other output formats will still show XML format giving the consisant clickable feel :-)
