### ISSUE TITLE
BlitzIndex is alerting for clustered indexes that are 16 bytes in size

### ISSUE THREAD

**Issue by TaraKizer** [BrentOzarULTD/SQL-Server-First-Responder-Kit#294]
For the "Index Hoarder: Wide clustered index (> 3 columns OR > 16 bytes)" section, I am still seeing clustered indexes with a size of 16 bytes. BlitzIndex should check for > 16 bytes and not >= 16 bytes since guids are 16 bytes. I did run the 7.1 version of CCC.

**Comment by BlitzErik** [comment]
That version of the collector is still running the older version of BlitzIndex. This issue is fixed in the newer version.

**Comment by BrentOzar** [comment]
Yeah, that's sp_BlitzIndex v2.02. The current one is v3. I'd done a few rounds of testing on that one and still can't catch problems with it. If we want to switch back to v3, there's a ticket in the CriticalCareCollector repo for it - let's talk over there.
